/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0-beta.9.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;
export const Booking = IDL.Record({
  'id' : IDL.Text,
  'contactInfo' : IDL.Text,
  'name' : IDL.Text,
  'preferredDate' : IDL.Text,
  'preferredTime' : IDL.Text,
  'timestamp' : Time,
  'packageId' : IDL.Text,
});
export const ContactMessage = IDL.Record({
  'id' : IDL.Text,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Text,
  'timestamp' : Time,
  'phone' : IDL.Text,
});
export const Instructor = IDL.Record({
  'id' : IDL.Text,
  'name' : IDL.Text,
  'photoUrl' : IDL.Text,
  'qualifications' : IDL.Text,
  'experienceYears' : IDL.Nat,
  'specializations' : IDL.Text,
});
export const SessionPackage = IDL.Record({
  'id' : IDL.Text,
  'duration' : IDL.Nat,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'price' : IDL.Nat,
});

export const idlService = IDL.Service({
  'addInstructor' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'addSessionPackage' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Nat],
      [],
      [],
    ),
  'deleteBooking' : IDL.Func([IDL.Text], [], []),
  'getBooking' : IDL.Func([IDL.Text], [Booking], ['query']),
  'getContactMessage' : IDL.Func([IDL.Text], [ContactMessage], ['query']),
  'getInstructor' : IDL.Func([IDL.Text], [Instructor], ['query']),
  'getSessionPackage' : IDL.Func([IDL.Text], [SessionPackage], ['query']),
  'listBookings' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
  'listContactMessages' : IDL.Func([], [IDL.Vec(ContactMessage)], ['query']),
  'listInstructors' : IDL.Func([], [IDL.Vec(Instructor)], ['query']),
  'listSessionPackages' : IDL.Func([], [IDL.Vec(SessionPackage)], ['query']),
  'submitBooking' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'submitContactForm' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'updateInstructor' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'updateSessionPackage' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Nat],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  const Booking = IDL.Record({
    'id' : IDL.Text,
    'contactInfo' : IDL.Text,
    'name' : IDL.Text,
    'preferredDate' : IDL.Text,
    'preferredTime' : IDL.Text,
    'timestamp' : Time,
    'packageId' : IDL.Text,
  });
  const ContactMessage = IDL.Record({
    'id' : IDL.Text,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Text,
    'timestamp' : Time,
    'phone' : IDL.Text,
  });
  const Instructor = IDL.Record({
    'id' : IDL.Text,
    'name' : IDL.Text,
    'photoUrl' : IDL.Text,
    'qualifications' : IDL.Text,
    'experienceYears' : IDL.Nat,
    'specializations' : IDL.Text,
  });
  const SessionPackage = IDL.Record({
    'id' : IDL.Text,
    'duration' : IDL.Nat,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'price' : IDL.Nat,
  });
  
  return IDL.Service({
    'addInstructor' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'addSessionPackage' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Nat],
        [],
        [],
      ),
    'deleteBooking' : IDL.Func([IDL.Text], [], []),
    'getBooking' : IDL.Func([IDL.Text], [Booking], ['query']),
    'getContactMessage' : IDL.Func([IDL.Text], [ContactMessage], ['query']),
    'getInstructor' : IDL.Func([IDL.Text], [Instructor], ['query']),
    'getSessionPackage' : IDL.Func([IDL.Text], [SessionPackage], ['query']),
    'listBookings' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
    'listContactMessages' : IDL.Func([], [IDL.Vec(ContactMessage)], ['query']),
    'listInstructors' : IDL.Func([], [IDL.Vec(Instructor)], ['query']),
    'listSessionPackages' : IDL.Func([], [IDL.Vec(SessionPackage)], ['query']),
    'submitBooking' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'submitContactForm' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'updateInstructor' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'updateSessionPackage' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Nat],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };