/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0-beta.9.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface SessionPackage {
    id: string;
    duration: bigint;
    name: string;
    description: string;
    price: bigint;
}
export interface Instructor {
    id: string;
    name: string;
    photoUrl: string;
    qualifications: string;
    experienceYears: bigint;
    specializations: string;
}
export type Time = bigint;
export interface ContactMessage {
    id: string;
    name: string;
    email: string;
    message: string;
    timestamp: Time;
    phone: string;
}
export interface Booking {
    id: string;
    contactInfo: string;
    name: string;
    preferredDate: string;
    preferredTime: string;
    timestamp: Time;
    packageId: string;
}
export interface backendInterface {
    /**
     * / Add instructor
     */
    addInstructor(id: string, name: string, qualifications: string, experienceYears: bigint, specializations: string, photoUrl: string): Promise<void>;
    /**
     * / Add session package
     */
    addSessionPackage(id: string, name: string, description: string, duration: bigint, price: bigint): Promise<void>;
    /**
     * / Delete booking
     */
    deleteBooking(id: string): Promise<void>;
    /**
     * / Get booking
     */
    getBooking(id: string): Promise<Booking>;
    /**
     * / Get contact message
     */
    getContactMessage(id: string): Promise<ContactMessage>;
    /**
     * / Get instructor
     */
    getInstructor(id: string): Promise<Instructor>;
    /**
     * / Get session package
     */
    getSessionPackage(id: string): Promise<SessionPackage>;
    /**
     * / List all bookings
     */
    listBookings(): Promise<Array<Booking>>;
    /**
     * / List all contact messages
     */
    listContactMessages(): Promise<Array<ContactMessage>>;
    /**
     * / List all instructors
     */
    listInstructors(): Promise<Array<Instructor>>;
    /**
     * / List all session packages
     */
    listSessionPackages(): Promise<Array<SessionPackage>>;
    /**
     * / Submit booking request
     */
    submitBooking(id: string, name: string, contactInfo: string, preferredDate: string, preferredTime: string, packageId: string): Promise<void>;
    /**
     * / Submit contact form
     */
    submitContactForm(id: string, name: string, email: string, phone: string, message: string): Promise<void>;
    /**
     * / Update instructor
     */
    updateInstructor(id: string, name: string, qualifications: string, experienceYears: bigint, specializations: string, photoUrl: string): Promise<void>;
    /**
     * / Update session package
     */
    updateSessionPackage(id: string, name: string, description: string, duration: bigint, price: bigint): Promise<void>;
}
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addInstructor(arg0: string, arg1: string, arg2: string, arg3: bigint, arg4: string, arg5: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addInstructor(arg0, arg1, arg2, arg3, arg4, arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addInstructor(arg0, arg1, arg2, arg3, arg4, arg5);
            return result;
        }
    }
    async addSessionPackage(arg0: string, arg1: string, arg2: string, arg3: bigint, arg4: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addSessionPackage(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addSessionPackage(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async deleteBooking(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteBooking(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteBooking(arg0);
            return result;
        }
    }
    async getBooking(arg0: string): Promise<Booking> {
        if (this.processError) {
            try {
                const result = await this.actor.getBooking(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBooking(arg0);
            return result;
        }
    }
    async getContactMessage(arg0: string): Promise<ContactMessage> {
        if (this.processError) {
            try {
                const result = await this.actor.getContactMessage(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getContactMessage(arg0);
            return result;
        }
    }
    async getInstructor(arg0: string): Promise<Instructor> {
        if (this.processError) {
            try {
                const result = await this.actor.getInstructor(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getInstructor(arg0);
            return result;
        }
    }
    async getSessionPackage(arg0: string): Promise<SessionPackage> {
        if (this.processError) {
            try {
                const result = await this.actor.getSessionPackage(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSessionPackage(arg0);
            return result;
        }
    }
    async listBookings(): Promise<Array<Booking>> {
        if (this.processError) {
            try {
                const result = await this.actor.listBookings();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listBookings();
            return result;
        }
    }
    async listContactMessages(): Promise<Array<ContactMessage>> {
        if (this.processError) {
            try {
                const result = await this.actor.listContactMessages();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listContactMessages();
            return result;
        }
    }
    async listInstructors(): Promise<Array<Instructor>> {
        if (this.processError) {
            try {
                const result = await this.actor.listInstructors();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listInstructors();
            return result;
        }
    }
    async listSessionPackages(): Promise<Array<SessionPackage>> {
        if (this.processError) {
            try {
                const result = await this.actor.listSessionPackages();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listSessionPackages();
            return result;
        }
    }
    async submitBooking(arg0: string, arg1: string, arg2: string, arg3: string, arg4: string, arg5: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.submitBooking(arg0, arg1, arg2, arg3, arg4, arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitBooking(arg0, arg1, arg2, arg3, arg4, arg5);
            return result;
        }
    }
    async submitContactForm(arg0: string, arg1: string, arg2: string, arg3: string, arg4: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.submitContactForm(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitContactForm(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async updateInstructor(arg0: string, arg1: string, arg2: string, arg3: bigint, arg4: string, arg5: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateInstructor(arg0, arg1, arg2, arg3, arg4, arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateInstructor(arg0, arg1, arg2, arg3, arg4, arg5);
            return result;
        }
    }
    async updateSessionPackage(arg0: string, arg1: string, arg2: string, arg3: bigint, arg4: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateSessionPackage(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateSessionPackage(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, uploadFile, downloadFile, options.processError);
}
